openapi: 3.0.3
info:
  title: Users API
  version: 1.0.0
servers:
  - url: https://api.example.com

paths:
  /users:
    get:
      operationId: listUsers
      tags: [users]
      responses:
        "200":
          description: A list of users
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
    post:
      operationId: createUser
      tags: [users]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"

  /users/{id}:
    get:
      operationId: getUserById
      tags: [users]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: A user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "404":
          description: Not found

  # NEW: route to test exclude patterns like /users/*/private
  /users/{id}/private:
    get:
      operationId: getUserPrivateById
      tags: [users, private]
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Private user info
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserPrivate"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    # Intentionally named "User" to test duplicates across specs.
    User:
      type: object
      required: [id, email]
      properties:
        id:
          type: string
          example: "u_123"
        email:
          type: string
          format: email
          example: "a@b.com"
        displayName:
          type: string
          example: "Ada Lovelace"

    CreateUserRequest:
      type: object
      required: [email]
      properties:
        email:
          type: string
          # format: email
        displayName:
          type: string

    UserPrivate:
      type: object
      required: [id, email, ssnLast4]
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        ssnLast4:
          type: string
          minLength: 4
          maxLength: 4
          example: "1234"

    Error:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          example: "FORBIDDEN"
        message:
          type: string
          example: "You do not have access to this resource."